### ISSUE TITLE
Limit in the number of found images

### ISSUE THREAD

**Issue by auxiliary** [teracow/bulk-google-image-download#1]
It seems there's a limit to the number of images it can find (100). Is that correct?

**Comment by teracow** [comment]
Yes, sounds correct. Limit is imposed by Google and out of my hands.

Sorry. :(

**Comment by teracow** [comment]
Minor update to this: I've found a way to increase the limit from 100 results up to 400. It may be possible to raise this even further (if I remember to get around to it).

I thought this was out of my hands - but then got bored and felt like a challenge. :)
